//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SydneyHUD_Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SydneyHUD_Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Download Cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel_download {
            get {
                return ResourceManager.GetString("Cancel_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Done_download {
            get {
                return ResourceManager.GetString("Done_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting to:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Install_Directory {
            get {
                return ResourceManager.GetString("Install_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select PAYDAY2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Selector_title {
            get {
                return ResourceManager.GetString("Selector_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Download:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start_download {
            get {
                return ResourceManager.GetString("Start_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SydneyHUD Installer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SydneyHUD_Installer {
            get {
                return ResourceManager.GetString("SydneyHUD_Installer", resourceCulture);
            }
        }
    }
}
